### ISSUE TITLE
Pattern incomplete when adapting to DLP Light Crafter 9000

### ISSUE THREAD

**Issue by zcshinee** [e841018/ERLE#1]
Hi,

I am using DLP Light Crafter 9000, which has a chip size of 1600x2560 instead of 1080x1920 but using the same DLPC9000 module. Thus, I modified your code in terms of image sizes (mostly just change all "1080, 1920" I can find to "1600, 2560"). Then when I upload the pattern, it turns out only exactly the right half of the pattern is displayed; and the left half of the DMD displayed a default TI image. 

Since the images are cut in rows, is it possible that something should be modified in "encode_row" function? I copied the function after my modification below.

It would be great if you can give some insights. Thanks.

`
def encode_row(row, same_prev):

    # bool array indicating if same as previous row, shape = (1920, )
    #     same_prev = np.zeros(1920, dtype=bool) if i==0 else image[i]==image[i-1]
    # bool array indicating if same as next element, shape = (1919, )
    same = np.logical_not(np.diff(row))
    # same as previous row or same as next element, shape = (1919, )
    # same_either = np.logical_or(same_prev[:1919], same)
    same_either = np.logical_or(same_prev[:2559], same)

    j = 0
    compressed = bytearray(0)
    # while j < 1920:
    while j < 2560:

        # copy n pixels from previous line
        if same_prev[j]:
            r = run_len(same_prev, j + 1) + 1
            j += r
            compressed += b"\x00\x01" + enc128(r)

        # repeat single pixel n times
        # elif j < 1919 and same[j]:
        elif j < 2559 and same[j]:
            r = run_len(same, j + 1) + 2
            j += r
            compressed += enc128(r) + bgr(row[j - 1])

        # single uncompressed pixel
        # elif j > 1917 or same_either[j + 1]:
        elif j > 2557 or same_either[j + 1]:
            compressed += b"\x01" + bgr(row[j])
            j += 1

        # multiple uncompressed pixels
        else:
            j_start = j
            pixels = bgr(row[j]) + bgr(row[j + 1])
            j += 2
            # while j == 1919 or not same_either[j]:
            while j == 2559 or not same_either[j]:
                pixels += bgr(row[j])
                j += 1
            compressed += b"\x00" + enc128(j - j_start) + pixels

    return compressed + b"\x00\x00"
`

**Comment by e841018** [comment]
Hi ,

I came up with something after you closed the issue, and maybe you've solved the problem already, but I hope this helps you.

I don't have a DLP9000, but I found some clues in `Table 2-106. Image Header` of [dlpu018](http://www.ti.com/lit/pdf/dlpu018):

> Image width (for dual controller DMDs this is half of the full width)

Since DLP9000 is driven by 2 DLPC900 controllers, and it seems that each row is cut into halves, I guess the DLPC900 that control the right half is working fine but the one for the left half is somehow buggy. It could be that you didn't specify the correct width in the image header, the left DLPC900 is not enabled, or the commands you sent are only accepted by the right DLPC900.

**Comment by zcshinee** [comment]
Hi,

Thanks for the quick reply. 

You are right that DLP9000 has two controllers and before I was only sending image to the master controller, so there is no display on the slave controller side. I found the following on the file you mentioned:

> When the DLPC900 is combined with a dual controller DMD, the user must load the images to both the I2C master and slave controllers by choosing the appropriate command in the command table. The full image must be divided in half where the I2C master controller gets the left half and the I2C slave controller gets the right half. Include the image header in the first line of both image halves where the image "width" is one half of the full array (native resolution) width.
